qiime/sdk/job.py, qiime/sdk/workflow.py, setup.py
This can be tested as follows from ``q2d3/demo/analysis-dir``.
```python
In [1]: from qiime.sdk import Workflow
In [2]: w = Workflow.from_markdown('/Users/caporaso/code/diversity/diversity/workflows/feature_table_to_pcoa.md')
In [5]: jpy = w.to_script({'feature_table': 'table.qtf', 'phylogeny': 'phylogeny.qtf'}, {'metric': 'unweighted_unifrac', 'depth': '50'}, {'distance_matrix': 'uu-dm.qtf', 'pcoa_results': 'uu-pc.qtf'})
In [7]: open('./test.py', 'w').write(jpy.markdown)
```
Then, exit ipython and:
```bash
$ python test.py
```
=> addition of Workflow.to_script

qiime/sdk/execution.py
fixes #35.
From ``q2d3/demo/analysis-dir`` this can be tested as follows:
```python
from qiime.sdk.execution import SubprocessExecutor
from qiime.sdk import Workflow
w = Workflow.from_markdown('/Users/caporaso/code/diversity/diversity/workflows/feature_table_to_pcoa.md')
e = SubprocessExecutor()
f = e(w, {'feature_table': 'table.qtf', 'phylogeny': 'phylogeny.qtf'}, {'metric': 'unweighted_unifrac', 'depth': '50'}, {'distance_matrix': 'uu-dm.qtf', 'pcoa_results': 'uu-pc.qtf'})
print(f.done())
f.result() # When f.done() == True, this will be a subprocess.CompleteProcess
```
=> stubs ExecutionContext and adds LocalSubprocessExecution

qiime/core/archiver.py, qiime/core/result_base.py, qiime/core/testing.py, qiime/plugin.py, qiime/sdk/__init__.py, qiime/sdk/artifact.py, qiime/sdk/plugin_manager.py, qiime/sdk/tests/test_artifact.py, qiime/sdk/tests/test_execution.py, qiime/sdk/tests/test_job.py, qiime/sdk/tests/test_plugin_manager.py, qiime/sdk/tests/test_workflow.py, qiime/sdk/visualization.py, qiime/sdk/workflow.py, qiime/tests/test_archive_format.py, qiime/tests/test_plugin.py
Parts of this were pair-programmed with @gregcaporaso.
Adds `Plugin.register_visualization` and `qiime.sdk.Visualization` class.
Refactored Artifact archive format logic into an Archiver class. Artifact and Visualization now have an archiver. Factored shared code into ResultBase ABC that Artifact and Visualization extend.
Renamed "archive format" to "data layout" to prevent confusion with actual Artifact/Visualization archive format (.qzf/.vzf).
=> ENH: initial visualization support

.travis.yml, qiime/sdk/plugin_manager.py
`__QIIME2_TEST_MODE__` -> `QIIMETEST`. The value of the env var can be anything (as was previously supported).
=> ENH: more useable test mode environment variable name

qiime/sdk/method.py, qiime/sdk/visualizer.py
Turns out it was a simple case of `__wrapped__` getting set and being the fallback for inspect when `__annotations__` doesn't exist. You must delete both in order to get rid of the annotations.
Formerly:
```json
In [1]: from qiime.plugin.diversity import ancom, beta_diversity
In [2]: ancom?
Type:           Visualizer
String form:    <qiime.sdk.visualizer.Visualizer object at 0x7f8d22bb45c0>
File:           ~/qiime2/qiime2/qiime/sdk/visualizer.py
Docstring:      <no docstring>
Call signature: ancom(output_dir:str, table:biom.table.Table, metadata:qiime.metadata.MetadataCategory) -> None
In [3]: beta_diversity?
Type:           Method
String form:    <qiime.sdk.method.Method object at 0x7f8d22b9b1d0>
File:           ~/qiime2/qiime2/qiime/sdk/method.py
Docstring:      <no docstring>
Call …
```
=> ENH: annotations removed on Methods and Visualizers

qiime/core/archiver.py, qiime/core/result_base.py, qiime/core/testing/visualizer.py, qiime/sdk/tests/test_artifact.py, qiime/sdk/tests/test_visualization.py, qiime/sdk/visualization.py
This is ready for review. 
Here's how I envision using this:
```python
In [1]: from qiime.sdk import Visualization
In [2]: Visualization.get_index_paths('pd-compare.qzv')
Out[2]: {'html': 'pd-compare/data/index.html'}
In [3]: Visualization.extract('pd-compare.qzv', '.')
Out[3]: '.'
In [5]: index_paths = Visualization.get_index_paths('pd-compare.qzv')
In [6]: output_dir = Visualization.extract('pd-compare.qzv', '.')
In [9]: import os
In [12]: html_path = os.path.join(output_dir, index_paths['html'])
In [13]: os.path.exists(html_path)
Out[13]: True
```
=> adds ResultBase.extract and Visualization.get_indices

qiime/core/archiver.py, qiime/core/result_base.py, qiime/sdk/artifact.py, qiime/sdk/tests/test_artifact.py, qiime/sdk/tests/test_visualization.py, qiime/sdk/visualization.py
Solves bug in Artifact/Visualization.load where previously the archive filepath was extracted on demand, resulting in buggy behavior if the filepath was deleted or modified after loading but prior to extraction. This problem is not easily solvable in a cross-platform compatible way so a new `.peek()` classmethod is provided to quickly retrieve an archive's metadata (e.g. UUID, type, and provenance) without extracting. `.load()` now extracts immediately.
Fixes #24.
=> ENH/BUG: add Artifact/Visualization.peek for quick inspection of archives

qiime/sdk/visualizer.py
Temporary solution for #73
```bash
In [2]: from qiime.plugin.feature_table.visualizers import summarize
In [3]: from qiime.sdk import Artifact
In [4]: summarize.async(table=Artifact.load('feature-table-frequency.qza')).result()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-a9c7a68dedce> in <module>()
----> 1 summarize.async(table=Artifact.load('feature-table-frequency.qza')).result()
<decorator-gen-140> in summarize(table)
/Users/Develop/Developer/work/qiime2/qiime/sdk/visualizer.py in async_wrapper(*args, **kwargs)
164             if plt.rcParams['backend'] == 'MacOSX':
165                 raise EnvironmentError(backend_error_template %
--> 166 …
```
=> FIX: Notify users of invalid matplotlib backend

qiime/sdk/method.py, qiime/sdk/tests/data/method_bad_input_section.md, qiime/sdk/tests/data/method_bad_outputs_section.md, qiime/sdk/tests/data/method_bad_parameters_section.md, qiime/sdk/tests/test_method.py
Adds basic checks for length of `type_tuple`, raises an exception if value is not two items long.
Questions:
- Do we need to raise separate errors for each metadata section? Or, could this be collapsed down into exception handling in `_split_type_tuple()`?
- If we are keeping the handling as-is, I imagine the error text could use a tune-up. Thoughts?
- Instead of saving temp MD files in the tests, should I be building this up as a permanent bad example in `qiime.core.testing`?
Thanks!
=> ENH: Method, validate markdown

LICENSE
LICENSE incorrectly stated it was under biocore.
=> DOC: Fix LICENSE holder

qiime/sdk/tests/test_visualizer.py, qiime/sdk/visualizer.py
Visualizers should only return `None` (Python implicit return value when not otherwise specified). This adds a quick check when calling the visualizer function, and if a value other than `None` is returned it raises a `ValueError` exception.
Questions:
- Thoughts on the verbiage for the exception?
Thanks!
=> ENH: Visualizers should not return anything

qiime/metadata.py
qiime.Metadata and qiime.MetadataCategory reprs use underlying DataFrame repr instead of JSON. Added HTML repr to qiime.Metadata.
Pair-programmed with @jakereps.
=> ENH: support for QIIME 1 feature metadata files in qiime.Metadata

qiime/core/archiver.py, qiime/core/tests/__init__.py, qiime/core/tests/test_archiver.py
This is a quick rough-cut of some tests that check for UTF-8 during encoding and decoding.
- Set `errors='strict'` in existing readers (`_load_version`, `_load_metadata`). This will ensure that a `TypeError` is raised if there is an encoding mismatch. Not sure if we need to raise our own exception at this point, but feel free to comment.
- Manually encode the payloads for the existing writers (`_save_version`, `_save_readme`, `_save_metadata`)
Questions:
- I used a dummy class for testing the relevant Archiver methods discussed above: thoughts on that? Maybe it makes more sense to set up a real Archiver instance for these tests. Let me know.
- Do we want to set a package constant (or class, etc.) that specifies the encoding to use? Right now `'utf-8'` is sprinkled throughout as arguments. …
=> TST: Check Archiver file encoding and decoding uses UTF-8.

qiime/sdk/plugin_manager.py, qiime/sdk/result.py, qiime/sdk/tests/test_plugin_manager.py
Moved private Artifact._get_data_layout to PluginManager as this functionality is generally useful (e.g. q2-types unit tests need access to it).
=> ENH: add PluginManager.get_data_layout()

qiime/core/util.py, qiime/sdk/result.py, qiime/sdk/tests/test_result.py, qiime/sdk/tests/test_visualization.py
Allows interfaces to use `Artifact.extension` or `Visualization.extension` to access the currently supported/recommended file extensions. 
Fix a few tests that were found to be using `visualization.qza` instead of `.qzv` through the warnings.
Example Output:
```shell
>>> Artifact.load('/Users/Develop/Developer/work/q2-types/q2_types/tests/data/feature-table-frequency.qza').save('test')
/Users/Develop/Developer/work/qiime2/qiime/sdk/result.py:236: UserWarning: The most widely supported and recommended file extension for a QIIME 2 Artifact is '.qza'. The Artifact will still be created, but the provided file extension can not be guaranteed to work with all QIIME 2 interfaces.
```
Resolves #7
Resolves #59
=> ENH: Add class-level extensions to Artifact, Visualization

qiime/core/type/__init__.py, qiime/core/type/primitive.py, qiime/plugin/__init__.py
I'm still green with the codebase, so apologize if this is off-base. I believe it's to the expectation. Have support for `int`, where `0 is False` and any other number (positive or negative) is `True`:
```python
In [1]: from primitive import Bool
In [2]: Bool.decode("10")
Out[2]: True
In [3]: Bool.decode("0")
Out[3]: False
In [4]: Bool.decode("True")
Out[4]: True
In [5]: Bool.decode("False")
Out[5]: False
```
Note: Python's `bool` casting is unexpected hence the direct checks against `"0"` and `"False"`. See below, where the expectation is that `bool` would operate like `int` but it actually just appears to test for a non-empty string:
```python
In [1]: bool("True")
Out[1]: True
In [2]: bool("False")
Out[2]: True
In [3]: bool("")
Out[3]: False
```
=> ENH: added Bool, addresses #115

qiime/core/callable.py, qiime/sdk/tests/test_method.py, qiime/sdk/tests/test_visualizer.py
Now that we have a Results class it is more consistent and easier to reason about if a Results object is always returned from an Action, regardless of the number of outputs. This will also simplify logic in interfaces (e.g. q2cli and qiime-studio).
=> ENH: Actions return Results object regardless of number of outputs

qiime/sdk/result.py, qiime/sdk/tests/test_result.py
`Artifact/Visualization.save()` now automatically appends the correct file extension (.qza/.qzv) if not present in the filepath that is saved to. A warning is no longer issued if the filepath doesn't have the correct extension. `.save()` returns the filepath that is saved to.
=> ENH: Artifact/Visualization.save() appends file extension automatically

qiime/core/archiver.py, qiime/core/tests/test_archiver.py
Archiver.save() now validates filepaths to provide useful error messages for common mistakes. Added corresponding unit tests.
Also removed FakeArchiver from unit tests in favor of a real Archiver instance.
=> ENH: Archiver.save() filepath validation

qiime/core/archiver.py, qiime/core/tests/test_archiver.py
Ignores files and directories starting with a dot. Files are ignored in a hidden directory even if they aren't hidden themselves (e.g. /foo/.bar/baz would be ignored).
=> ENH: ignore dotfiles in Archiver.save()

qiime/core/archiver.py, qiime/core/util.py, qiime/sdk/__init__.py, qiime/sdk/plugin_manager.py, qiime/sdk/result.py, qiime/sdk/util.py
Added `PluginManager.iter_entry_points()` classmethod for getting unloaded entry points (needed for CLI optimizations).
Moved `qiime.core.util.parse_type/parse_format/UnknownTypeError` to `qiime.sdk.util` (also accessible from `qiime.sdk`). This move was also necessary for CLI optimizations. It also avoids circular import errors that previously had to be worked around. 👌
=> ENH/REF: add PluginManager.iter_entry_points(), add qiime.sdk.util

qiime/core/testing/plugin.py, qiime/plugin/plugin.py, qiime/sdk/plugin_manager.py, qiime/sdk/util.py
A "bug" was discovered while removing the duplicate BIOMv1 directory type registration from `q2-types`. The framework loses the ability to know this format still exists, as it was previously scraping transformer annotations, and semantic type to format registrations.
This PR adds explicit format registration to plugin objects, and makes them accessible through the `PluginManager`, a nice side effect is that this greatly reduces the runtime of `qiime.sdk.util.parse_format`.
=> ENH: Add explicit format registration to Plugin objects

qiime/core/archiver.py, qiime/sdk/tests/test_artifact.py, qiime/sdk/tests/test_result.py, qiime/sdk/tests/test_visualization.py
Previously returned the output directory the Result was extracted in. Now
returns the absolute path to the directory that was extracted (i.e. the
Result's UUID root directory).
This change is necessary to support https://github.com/qiime2/q2cli/issues/72
=> ENH: Result.extract returns path to extracted directory

qiime/core/type/signature.py, qiime/core/type/tests/test_signature.py
Previously the `inputs` and `parameters` property of `Signature` objects
created by the `.from_function` alternate constructor did not respect the order
of the original function signature. Now these properties are always
`collections.OrderedDict` instances.
=> ENH: Signature now matches order of function sig.

qiime/sdk/result.py
Adds `Result.export_data` to `qiime.sdk` for exporting the data directories to the user's filesystem.
=> ENH: Add Result.export_data to sdk

README.md, qiime/core/testing/plugin.py, qiime/plugin/tests/test_plugin.py, qiime/sdk/__init__.py
Removed `qiime.sdk.HELP_URL`, `CITATION`, and `CONDA_CHANNEL` as these variables were only used a couple of places in q2cli and don't seem to have much value. For example, using `HELP_URL` made it difficult to identify broken links (e.g. there were two broken links in q2cli that weren't searchable).
=> DOC: update to use canonical urls

qiime/plugin/model/directory_format.py
Trying to import using a `source_format` as a Directory Format is failing due to the glob grabbing hidden `.DS_Store` files and failing to validate.
``` bash
ValueError: Unrecognized file (InPath('/var/folders/t1/qdtgl9t964s0s_8yfsfx9d_c0
000gq/T/qiime2-archive-_4ak2iap/f00c26ac-4cea-4620-9f35-249024bd241c/data/.DS_St
ore')) for 'BIOMV100DirFmt'.
```
=> FIX: Directory Formats fail to validate from globbed hidden files

qiime/plugin/testing.py
Discovered a pattern while making `q2_types` tests, and this helper cut over 40 lines of transformer test boilerplate from a single subpackage.
=> ENH: Add Transformer Test Helper to TestPluginBase

qiime/core/archive/format/tests/test_util.py, qiime/core/archive/format/tests/test_v0.py, qiime/core/archive/format/util.py, qiime/core/archive/format/v0.py, qiime/core/archive/format/v1.py
`artifact_version` allows for contextual monkey-patching of the Archive
version used by the framework. This is useful for testing previous
archive versions for backwards-compatibility, etc.
This also makes several changes to the `v0` format for compatibility with the `v1` API.
=> ENH: Add format switch ctx mgr

qiime/core/type/signature.py, qiime/plugin/plugin.py, qiime/sdk/action.py
Allow optional help text strings to be associated with action parameters.
```python
In [1]: from qiime.plugins.test_plugin.methods import blocking_test
In [2]: blocking_test.signature
Out[2]: 
inputs:
table: ParameterSpec(qiime_type=FeatureTable[Frequency], view_type=<class 'biom.table.Table'>, default=NOVALUE, help_text=NOVALUE)
parameters:
timeout: ParameterSpec(qiime_type=Int, view_type=<class 'int'>, default=NOVALUE, help_text='The amount of time to wait before continuing execution of the method.')
outputs:
rarefied_table: ParameterSpec(qiime_type=FeatureTable[Frequency], view_type=<class 'biom.table.Table'>, default=NOVALUE, help_text=NOVALUE)
```
=> ENH: Add help_text support to action signatures

qiime2/sdk/action.py
Stumbled upon this issue while working on something else. Matplotlib backend `MacOSX` also works as `macosx`, but this check is checking case-sensitive parameters. 
Modify and compare it against a lowercase string instead.
=> BUG: Normalize matplotlib backend check

qiime2/__init__.py
`qiime2.__release__` is a string containing the "train release" in `<year>.<month>` format. It is `__version__` with patch and pre/post-release tags stripped.
For example:
```
__version__ = '2017.2.0.dev0'
__release__ = '2017.2'
```
=> ENH: add `qiime2.__release__` API

README.md, qiime2/core/testing/plugin.py, qiime2/plugin/plugin.py, qiime2/plugin/tests/test_plugin.py
* Added `description` and `short_description` params to plugin class
* Each has default value of None so we retain backwards-compatibility
* Added default values for each in the style of the default values for the other optional params in that class 
* Added basic unit tests for each in the style of the unit tests I saw for plugins
* Added a link to the Markdown README for improved readability
This is in response to [issue #81](https://github.com/qiime2/qiime2/issues/81#issuecomment-279822099)
=> plugins should have a description that can be used by interfaces

qiime2/core/testing/plugin.py, qiime2/core/testing/type.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/plugin_manager.py, qiime2/sdk/tests/test_plugin_manager.py
Adds `qiime2.sdk.PluginManager.importable_types` read-only property, which is the set of concrete semantic types that are importable (i.e.  concrete type expressions that are registered with a directory format).
Also made testing sandboxed, such that when the QIIMETEST environment variable is set, only the framework's builtin `dummy-plugin` is discovered. If QIIMETEST is not set, all available plugins are discovered, with the exception of `dummy-plugin`.
This sandboxing solves a couple of issues:
- Unit tests are more robust and easier to write, because when tests are run, only the framework's `dummy-plugin` is discovered.  Previously tests had to be written so they would pass even if other plugins were discovered.
- q2-dummy-types and the framework's `dummy-plugin` are incompatible …
=> ENH: qiime2.sdk.PluginManager.importable_types; sandboxed tests

ci/recipe/meta.yaml, setup.py
Also specify acceptable versions of Python in the recipe.
Reference: https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages
=> CI: noarch python in conda recipe

qiime2/core/testing/format.py, qiime2/core/testing/plugin.py, qiime2/core/testing/transformer.py, qiime2/core/transform.py, qiime2/sdk/tests/test_result.py
When importing it is sometimes the case that the user is importing a directory
and both the supplied view_type and the registered view_type are
SingleFileDirectoryFormats with only a single transformer between their
respective file-formats. This should be fine, but the implicit transformers of:
XDirFmt -> X => Y -> YDirFmt
were not working (where -> is an implicit transformer and => is a registered
one).
=> BUG: fix SingleFileDirectoryFormat transformation

qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/core/testing/visualizer.py, qiime2/core/type/signature.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_visualizer.py
Methods and visualizers are no longer required to accept at least one input artifact.
Fixes #261.
=> ENH: support methods/visualizers without input artifacts

qiime2/core/testing/util.py, qiime2/sdk/tests/test_artifact.py, qiime2/sdk/tests/test_result.py, qiime2/sdk/tests/test_visualization.py
This really only comes up if you set your `TMPDIR` to `.` while running the test suite.
=> TST: fix overzealous tests for extract

qiime2/tests/test_util.py, qiime2/util.py
Making filesystem utilities isn't much fun.
This will replace uses of `os.link` in plugins.
=> ENH: add duplicate util

qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py, qiime2/core/testing/util.py, qiime2/metadata.py, qiime2/tests/data/metadata-no-columns.tsv, qiime2/tests/data/metadata.tsv, qiime2/tests/test_metadata.py
Added ``qiime2.Metadata.merge`` method for merging one or more ``Metadata`` objects using an inner join. Source artifacts are tracked on merged metadata to preserve provenance (source artifacts can be accessed with ``Metadata.artifacts`` property).
A few other misc changes that came up during implementation:
- ``Metadata`` now disallows empty metadata (i.e. metadata without any rows).
- ``Metadata`` explicitly supports metadata without columns (i.e. index-only metadata).
- Added ``Metadata.__eq__``/``__ne__`` for easier unit testing.
- Added ``qiime2.core.testing.util.ReallyEqualMixin`` for testing ``__eq__``/``__ne__`` implementations.
- Added some missing unit tests to ``Metadata``/``MetadataCategory`` as I noticed them (not exhaustive in any way).
Fixes #269.
=> ENH: add method for merging Metadata objects

qiime2/sdk/action.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_visualizer.py
At the moment, when `?` is called on any QIIME 2 action, this is the help text that Jupyter produces (my examples use ``feature_table.rarefy``):
This is extremely general, and not very helpful to the user. The only arguably useful information it provides is the arguments the function requires. 
After my changes, this is the help text that Jupyter produces:
As you can see, now there is more information regarding the Method. The user sees that it is a QIIME 2 Method object, and is given some useful help text. 
fixes #278 
@jairideout, @ebolyen, @thermokarst, very simple, ready for review.
=> ENH: Adds basic docstring to Actions

qiime2/sdk/action.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_visualizer.py
As of now, when ``?`` is called on a QIIME 2 Method or Visualizer, this is the general format of the help text produced by Jupyter:
This help text is helpful, although it is missing a key component that is now tied to all Methods and Visualizers, due to some new Python functionality, that component being _annotations_. This PR adds annotations (including return annotations) and testing to Actions.
Calling ``?`` with the PR in effect:
=> ENH: Adds annotations to Actions

qiime2/core/type/signature.py
Discovered while updated q2studio.
This should *probably* have unit-tests
=> BUG: fix optional support in decode_parameters

qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/plugin/tests/test_plugin.py
Adding these methods for testing q2cli's optional metadata support.
=> TST: add testing methods for optional metadata and optional metadata category

qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py, qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/core/type/signature.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/action.py, qiime2/sdk/tests/test_method.py
Methods and visualizers now support optional artifacts. If an artifact is optional the only supported default value is `None`.
With this change, signature inputs and parameters are now allowed to be declared in any order (previously inputs were required to be followed by parameters, and they were not allowed to be mixed).
Removed `Signature.defaults` property in favor of using the `ParameterSpec` objects available within `Signature`.
Fixes #235.
=> ENH: support optional artifacts

qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/action.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_visualizer.py
Previously, calling `?` on a QIIME 2 Action (`merge_mappings`) yielded the following call docstring:
There could be much more information in this docstring, so I have added functionality which creates a full Numpydoc-compliant docstring for any QIIME 2 Method. Calling `?` on the Action now yields:
@jairideout
fixes #280
=> ENH: Adds full Numpydoc-compliant docstring to Actions

.travis.yml, Makefile
Previously:
```
QIIMETEST= make test
```
Now:
```
make test
```
:tada:
Also removed the `test-cov` target because coverage isn't set up for this package (yet).
=> ENH: let `make test` handle QIIMETEST env var

Makefile, scripts/activate_matplotlib.sh, scripts/deactivate_matplotlib.sh
This relies on the fact that QIIME 2 is officially distributed with
`conda` - the `make install` directive will set up `conda` activate and
deactivate hooks responsible for setting the appropriate matplotlib
environment variables.
---
I tested this locally by running the following build command:
```bash
$ conda build \
-c https://conda.anaconda.org/qiime2 \
-c https://conda.anaconda.org/conda-forge \
-c defaults \
-c https://conda.anaconda.org/bioconda \
-c https://conda.anaconda.org/biocore \
--override-channels --python 3.5 --output-folder ~/Desktop/bldr ci/recipe
```
Then, unpacking a viewing the built bz2:
```bash
$ tree ~/Desktop/bldr/osx-64/qiime2-2017.9.0.dev0+4.g1af7d13-py35_0/ -L 4
/Users/matthew/Desktop/bldr/osx-64/qiime2-2017.9.0.dev0+4.g1af7d13-py35_0/
├── etc
│   └── conda …
```
=> ENH: Set matplotlib backend

qiime2/metadata.py, qiime2/tests/data/metadata/empty-rows.tsv, qiime2/tests/test_metadata.py
Empty rows are now ignored, similar to how blank lines and comments are ignored. In this case, an "empty row" is a row consisting only of empty cells (i.e. only tab characters).
Fixes #336.
=> BUG: support empty rows in `Metadata.load`

qiime2/core/type/primitive.py
Currently, the repr for a range [1:] with no upper value is the same as the repr for a range [:1] with no lower value.
In [1]: from qiime2.core.type.primitive import Range
In [2]: repr(Range(1, None)) == repr(Range(None, 1))
Out[2]: True
Proposed change forces the repr to include both start and end positions, even if they are the same as the default. This will allow the repr to differentiate between the two ranges in the case above (as when used in parse_type to generate a type from a repr string).
=> Update primitive.py for Range to fix repr bug

qiime2/core/archive/__init__.py, qiime2/core/archive/archiver.py, qiime2/core/archive/format/v2.py, qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py, qiime2/core/path.py, qiime2/core/testing/pipeline.py, qiime2/core/testing/plugin.py, qiime2/core/testing/transformer.py, qiime2/core/type/signature.py, qiime2/plugin/__init__.py, qiime2/plugin/plugin.py, qiime2/plugin/tests/test_plugin.py, qiime2/plugins.py, qiime2/sdk/__init__.py, qiime2/sdk/action.py, qiime2/sdk/context.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_pipeline.py, qiime2/tests/test_artifact_api.py
TODO:
Pipelines work otherwise! And cleanup is handled even when calling with `.async`
=> ENH: adds basic Pipeline actions

qiime2/core/testing/pipeline.py, qiime2/plugin/model/directory_format.py, qiime2/plugin/model/file_format.py, qiime2/sdk/tests/test_artifact.py
Commit 1:
Wrapped error messages from the underlying file or directory format were being displayed with `%r` instead of `%s`, making them difficult to read. Also added some newline padding to separate the wrapper's preamble text from the actual error message.
Before:
After:
Commit 2:
Fix "ambiguous variable name" error from new flake8.
=> BUG: fix misformatted error messages from file and directory format `validate`

qiime2/core/archive/archiver.py, qiime2/core/archive/format/v3.py, qiime2/core/archive/provenance.py, qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/core/type/__init__.py, qiime2/core/type/collection.py, qiime2/core/type/grammar.py, qiime2/core/type/primitive.py, qiime2/core/type/semantic.py, qiime2/core/type/tests/test_collection.py, qiime2/core/type/tests/test_grammar.py, qiime2/plugin/__init__.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/action.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_method.py
`Set` and `List` are no longer primitive types, they are collection types. This
means they can be used on primitives (with the exception of metadata) or
semantic types. This enables variadic input artifacts in the framework.
~~**This is still under-tested. I'm going to be making changes to the CLI to make sure this works before returning to this PR**~~
=> ENH: adds collection types

qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata.py
Discussed with @antgonza and @gregcaporaso. The requirement that IDs or column names cannot contain case-insensitive duplicates may be too restrictive (@antgonza had alleles as column names in his example).
The code now performs exact string matching when checking for duplicates on either axis.
=> MAINT: remove case-insensitive duplicates check for IDs and column names

qiime2/core/archive/tests/test_provenance.py, qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_artifact.py
Removed `Metadata.from_artifact` in favor of `Artifact.view(Metadata)`, which now tracks the source artifact (important for provenance).
Discussed with @ebolyen; there's no need to have two APIs that do the same thing, and using the view API is preferred since `Metadata` doesn't need to be special-cased.
Related to discussion in https://github.com/qiime2/q2-feature-table/issues/136 regarding `Artifact.view(Metadata)` not tracking the source artifact, which is now fixed.
=> ENH: remove Metadata.from_artifact in favor of Artifact.view(Metadata)

qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata.py
Previous behavior of `Metadata.merge` allowed zero `Metadata` objects as input, which would result in a copy of the `Metadata` object being called upon (i.e. `self`).
New behavior is to raise a `ValueError` if no `Metadata` objects are provided to merge into `self` (there is nothing to merge in that case).
@thermokarst found a bug in q2cli related to this behavior: a merge was always happening even if only a single `Metadata` object was provided as input, making the `id_header` normalize to `'id'`, which is probably not what users would expect to happen.
=> ENH: `Metadata.merge`: disallow merging nothing

qiime2/metadata/metadata.py
Fixes #353 
---
This change doesn't do anything to prevent users from providing unquoted reserved keywords in their queries, but it provides a path forward when they do by:
1. Alerting the user to the need to quote reserved keywords, and provides them a URL to learn more about that.
2. Chains the original `sqlite3` driver exception. This is less helpful for the reserved keyword case, but is pretty cool in general, because it shows things like missing columns, or other syntax errors:
```bash
qiime feature-table filter-samples \
--i-table table.qza \
--m-metadata-file keywords.tsv \
--p-where "Peanut='thedog'" \
--o-filtered-table reserved.qza \
--verbose
Traceback (most recent call last):
File "/Users/matthew/src/qiime2/qiime2/qiime2/metadata/metadata.py", line 445, in get_ids …
```
=> ENH: More clear error message when running SQL

qiime2/metadata/base.py, qiime2/metadata/io.py, qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata.py, qiime2/metadata/tests/test_metadata_column.py
Includes the following changes:
- Extensive Metadata/MetadataColumn API unit tests. Coverage is now at 100% for the `qiime2.metadata` subpackage.
- Many of the API-level error messages have been improved for clarity.
- Duplicated code between MetadataReader, Metadata, and MetadataColumn has been refactored to be DRY.
- `Metadata.filter_columns()` now ignores missing data in its uniqueness/zero-variance filters.
- Added `MetadataColumn.__eq__/__ne__` methods.
Note to reviewer: the diff is confusing in some places because I shuffled the ordering of some methods (and their associated unit tests) to be consistent between classes and match method organization used in other parts of the framework.
=> ENH/TST/REF: Metadata API tests/coverage; improved error messages; refactored code

ci/recipe/meta.yaml, qiime2/__init__.py, qiime2/citations.bib, qiime2/core/archive/archiver.py, qiime2/core/archive/format/tests/test_util.py, qiime2/core/archive/format/v4.py, qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_archiver.py, qiime2/core/archive/tests/test_citations.py, qiime2/core/cite.py, qiime2/core/format.py, qiime2/core/testing/citations.bib, qiime2/core/testing/plugin.py, qiime2/core/testing/transformer.py, qiime2/core/transform.py, qiime2/core/util.py, qiime2/plugin/__init__.py, qiime2/plugin/cite.py, qiime2/plugin/model/base.py, qiime2/plugin/plugin.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/action.py, qiime2/sdk/plugin_manager.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_artifact.py, qiime2/sdk/tests/test_result.py, qiime2/sdk/tests/test_visualization.py, qiime2/sdk/tests/test_visualizer.py, setup.py
fixes #344 
fixes #354 
fixes #113 
Transformers are added for methods (input and output), visualizers (input only), and import (output only). Pipelines do not have transformers by nature, and so do not create that section in action.yaml.
Citations are bibtex files with a YAML type `!cite '<citation key>'`. There is a new object in `qiime2.plugin` called `Citations` which is just a dictionary, but it has a `.load()` method which will load a `citations.bib` file from somewhere. See this PR for example: https://github.com/qiime2/q2-emperor/pull/59
TODO:
Questions:
- `plugin.citation_text` is expected by a bunch of things. It would be best to just remove it entirely and use the new `citations`, this will break a bunch of things. 
- I don't have a way to format the bibtex, does that matter at …
=> ENH: adds citations and transformers to provenance

qiime2/__init__.py, qiime2/jupyter/__init__.py, qiime2/jupyter/handlers.py, qiime2/jupyter/hooks.py, qiime2/jupyter/template.py, qiime2/sdk/result.py
fixes #340 
This supports `base_url` config so it should work with JupyterHub. 
The `_html_repr_` is able to provides instructions:
- when the extension isn't installed.
- when the kernel has been restarted and the page reloaded (i.e. viz is out of scope)
I think this will be of interest to @ElDeveloper, @bassio, and @jakereps.
I've done a bunch of local testing, but this could use more!
To install, just run:
```bash
jupyter serverextension enable --py qiime2 --sys-prefix
```
-or-
repr a QIIME 2 visualization which will produce the above instructions.
=> ENH: adds notebook server-extension for viewing results

qiime2/sdk/tests/test_util.py, qiime2/sdk/util.py
Perhaps a description might be useful. Basically, this adds a new method to retrieve all plugins and their actions with a given input. This could be helpful to figure out which actions can be applied on a given input.
=> add sdk.util.artifact_actions

qiime2/core/testing/method.py, qiime2/core/testing/visualizer.py, qiime2/metadata/tests/test_io.py, qiime2/metadata/tests/test_metadata.py, qiime2/metadata/tests/test_metadata_column.py, qiime2/sdk/action.py, qiime2/sdk/results.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_pipeline.py, qiime2/sdk/tests/test_visualizer.py, qiime2/sdk/util.py, versioneer.py
Numerous minor updates for compliance with flake8 v3.6, as discussed in #415.
Note: flake8 has been disabled in versioneer.py.
=> Update for flake8 v3.6

qiime2/core/archive/archiver.py, qiime2/core/archive/format/v5.py, qiime2/core/archive/tests/test_archiver.py, qiime2/core/exceptions.py, qiime2/core/tests/test_util.py, qiime2/core/util.py, qiime2/plugin/model/base.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_artifact.py, qiime2/sdk/tests/test_result.py, qiime2/sdk/tests/test_visualization.py, qiime2/sdk/tests/test_visualizer.py
This commit adds a 'checksums.md5' file to the root of an archive.
The file is formatted with the md5sum format:
\<hex-hash>\<space>\<space or asterisk>\<escaped filename>\<newline>
Filename escaping handles backslash and newline. In the event those are
present, the backslash is doubled and the newline becomes `\n`.
Additionally if escaping is required, then an additional backslash
precedes the \<hex-hash> to indicate the filename is escaped.
See:
https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html
for more details.
**TODO**:
=> NEW: adds checksums to archive structure

qiime2/core/type/signature.py, qiime2/sdk/tests/test_method.py
closes #252 
Is this readable enough in cases like below, where there are multiple subtypes? We could probably parse "type [x | y | z]" into "type[x] or type[y] or type[z]".
=> Updates TypeError Message to improve readability for naive users

qiime2/core/type/semantic.py
Typo corrections. Also attempts to wrangle some confusing language for better clarity in dev docs.
=> MAINT: Copy edits to SemanticTypes() docstring

qiime2/core/testing/plugin.py, qiime2/core/type/signature.py, qiime2/sdk/tests/test_action.py, qiime2/sdk/tests/test_bad_inputs.py, qiime2/sdk/tests/test_method.py, qiime2/sdk/tests/test_visualizer.py
fixes #437 
- Fixes type mismatch exception for primitives (e.g. when a string is passed where an int is expected)
- Customizes type mismatch error messages to better describe the user error
- Adds tests to support these changes
=> BUG: Fixes type mismatch exception for primitives

CONTRIBUTING.md
This guide is not up to date, and is causing more confusion than it is worth right now. The "main" contributing guide can be found in the `.github` dir, anyway.
=> MAINT: Remove outdated contributing guide

ci/recipe/meta.yaml
0.25.x is out, but let's save that jump for the 2019.10 release cycle...
=> HACK: pinning pandas 0.24.2 for 2019.7 release

qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py, qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/plugin/tests/test_plugin.py
`UnionExpr` doesn't have a `name`, so this bit of the provenance handler was exploding. By switching to the `.get` accessor, we get to opt into the pre-existing identity fallback behavior.
=> BUG: Handle primitive unions in provenance

qiime2/plugin/model/file_format.py, qiime2/plugin/model/tests/test_file_format.py
Closes #482 `_FileFormat` objects now have a `.view` method allowing for easy transformation of `_FileFormat` subclasses without them needing to be turned into `BoundFile` objects. I am unsure of how to test this code. Should `.view` tests be added to the tests for every `_FileFormat` subclass testing each of their transformers? Should the `dummy_plugin` be used to test the transformers of the subclasses of `_FileFormat` in `dummy_plugin`?
=> IMP: Add .view method to _FileFormat

ci/recipe/meta.yaml
Unpin pandas to determine build issues regarding QIIME 2 plugins and busywork.
=> HACK: Unpin pandas to v0.25.1 to determine plugin issues

qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata.py, qiime2/metadata/tests/test_metadata_column.py
Closes #478. Strips all white space from all pieces of the Metadata
=> IMP: Metadata constructor now strips whitespace

qiime2/core/testing/plugin.py, qiime2/plugin/plugin.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/plugin_manager.py, qiime2/sdk/tests/test_plugin_manager.py
Exposes plugin level list (set technically) of importable types for easy access in coming changes to docs/cli/artifact API. I can make this happen with formats as well on this or another branch.
=> NEW: Expose plugin level importable types set through sdk

qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py
This PR addresses the issues that some users encounter regarding timezone information. This fix bypasses the `ValueError` that is shown and simply sets the timezone to none, which produces date & time, without any timezone information.
See issue #510 for more details.
=> Fall back for tzlocal failure

qiime2/core/type/util.py
When a TypeMap generates a type such as Bool % Choices(False) | Bool,
parse_primitive will will attempt to strip the predicates to recieve a
base type. However this resulted in Bool | Bool which caused the logic
within parse_primitive to fail to recognize the coercion priority giving
us a floating point 0.0 type instead of False.
Normalizing the UnionExp after stripping predicates corrects this issue,
giving us a single Bool type that is recognized by the internal logic.
=> BUG: fix behavior of parse_primitive with TypeMap

qiime2/plugins.py, qiime2/sdk/tests/test_usage.py, qiime2/sdk/usage.py
@andrewsanchez pointed out to me that there was some clumsy inversion of SDK API in `sdk.usage.UsageOutputNames` - this PR attempts to reconcile that. Now usage drivers can expect to receive a dict of action inputs (parameter name as key, value as, ahem, the value), and a dict of action outputs (parameter name as key, scope ref name as value). I think this makes it a bit simpler to reason about, as an SDK dev.
=> IMP: Invert UsageOutputNames SDK API

qiime2/plugin/testing.py
Replaces and closes #494 
Fixes #492 by adding documentation.
=> DOC: clarify intent of test harness machinery

qiime2/core/testing/examples.py, qiime2/core/testing/plugin.py, qiime2/sdk/tests/test_usage.py, qiime2/sdk/usage.py, qiime2/tests/test_artifact_api.py
PR adds checks to ensure that we are able to handle `ScopeRecord` instances within a list or set.
When adding a usage example to `q2-feature-table`, it was discovered that the framework handled lists and `ScopeRecord` types, but could not take in lists or sets with ScopeRecord types as values within that list/set.
This PR adds two conditions that update the `value` variable, using set or list comprehension (depending on the case), to handle such cases.
@thermokarst Is there anything you would recommend for testing these changes moving forward?
Thanks in advance.
=> FIX: Added condition for list and set in build opts

qiime2/plugin/model/directory_format.py
close qiime2/q2-types#218 by tightening up the regex used to validate filenames.
=> BUG: Improve pathspec regex to prevent incorrect filenames

qiime2/metadata/io.py
Closes #537. It seemed to me like the simplest way to resolve this issue would be adding a short note that metadata files must be tab and not comma separated. Hopefully people will be able to see this note and quickly realize what the issue is if they attempt to use a csv as metadata.
=> MAINT: Update error message to point out common mistake

qiime2/core/testing/method.py, qiime2/core/testing/plugin.py, qiime2/core/testing/tests/test_mapped_actions.py, qiime2/core/type/signature.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/tests/test_util.py
Evan and I discovered a bug while working on caporaso-lab/genome-sampler#49 that prevents the use of TypeMatch with a List[Union] or Set[Union]. This fixes that bug.
Next step, add a test.
=> BUG: Fix bug with TypeMatch and Set or List Union

qiime2/core/testing/examples.py, qiime2/plugin/__init__.py, qiime2/sdk/usage.py
This is a breaking API change. I think it will be helpful for a few
reasons:
1) Importing the UsageAction/Inputs/OutputNames from qiime2.plugin was
weird and a little confusing, IMO.
2) This feels more consistent to me with other elements of Usage
3) This will simplify writing sphinx-ext-qiime2's usage extensions
---
I am open to other ideas, and also am interested in discussing names.
cc @andrewsanchez && @ebolyen
=> API: usage, inject the action helpers, too

qiime2/core/archive/provenance.py, qiime2/core/archive/tests/test_provenance.py, qiime2/core/path.py, qiime2/core/tests/test_path.py
This changeset attempts to address some longstanding issues we've seen crop up on the forum from time to time:
- https://forum.qiime2.org/t/qiime-tools-import-on-cluster/17531
- https://forum.qiime2.org/t/error-while-runing-dada2/16600
- https://forum.qiime2.org/t/qiime2-installation-and-run-error/4766
- https://forum.qiime2.org/t/out-of-disk-space-error/5736
This has been a tricky one to debug though, since it seems to be specifically tied to the [BeeGFS filesystem](https://en.wikipedia.org/wiki/BeeGFS). I finally figured out how to reproduce this error though, using the following repo (plus patch; I also had to manually rebuild the beegfs client and launch the system service):
https://github.com/jeremysj/beegfs-sandbox/
```patch
diff --git a/roles/beegfs_client/tasks/main.yml …
```
=> bug: networked filesystem race conditions

qiime2/metadata/io.py, qiime2/metadata/metadata.py, qiime2/metadata/tests/test_io.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_result.py
.save() method now includes the extension argument, which takes string values as input.
This argument has been added for Metadata, Artifact, and Visualization classes.
Default values (if left blank) for each class are as follows:
Metadata: blank
Artifact: .qza
Visualization: .qzv
Additionally, Metadata.save() will now return the filepath (including optional extension), just as Artifact and Visualization currently do.
Unit tests have been implemented for the above changes, as well as docstring additions.
=> IMP: save() updates: adding optional file extension argument

qiime2/core/tests/test_util.py
Confirms `from_checksum_format()`'s handling of leading-backslash filepaths, like those in the last couple lines here:
=> Tests from_checksum_format() on filepaths with leading \'s

qiime2/core/testing/examples.py, qiime2/plugins.py, qiime2/sdk/tests/test_usage.py, qiime2/sdk/usage.py
I think this will help with TypeMap usage implementations.
=> NEW: adds assert_output_type to Usage API

qiime2/plugins.py
This may be overkill, but I really like how the output ended up.
With `str` view_type:
With `class` view_type:
=> BUG: class view_type in Usage.import_from_format

qiime2/core/tests/test_validate.py, qiime2/core/validate.py
Discovered in q2-fmt. When multiple validators exist, the "source" `data` was overwritten within a loop, causing the next iteration to fail as `data` would have the wrong type for the next selected transformer.
=> BUG: semantic validation's transformations

qiime2/core/testing/plugin.py, qiime2/core/type/primitive.py, qiime2/core/type/signature.py, qiime2/core/type/tests/test_primitive.py
Fixes a long-standing annoyance for output registration.
Also, prevents the plugin author from accidentally creating a `set` of tuples as the output registration.
Sorts `set`s provided to `Choices` so that interfaces which cache the types will maintain a consistent ordering.
=> NEW/MISC: allow dict for output registrations and error/sort on sets

qiime2/metadata/metadata.py, qiime2/metadata/tests/test_metadata_column.py
Greetings,
While working on issue #520 related to migration to python 3.9 in the Debian project, I caught an issue specific to 32-bits CPU architectures.  On 64-bits CPUs, the _pandas.dtype_ returned for integers is a plain _int_ 64 bits wide.  However, on 32 bits machines, the type is returned as _int64_ to differenciate from plain _int_, which I suppose would be 32 bits wide in such context.
Due to this, when running the test suite on 32-bits CPU architectures, the error output includes several instances of errors such as the following:
```
======================================================================
ERROR: test_decode_numeric_value (qiime2.core.type.tests.test_primitive.TestMetadataColumn)
----------------------------------------------------------------------
Traceback (most …
```
=> Compatibility with 32-bits CPU architectures

qiime2/metadata/io.py, qiime2/metadata/tests/data/valid/missing-insdc-no-directive.tsv, qiime2/metadata/tests/test_io.py
There was a bug in `Metadata.load()` where a set `default_missing_scheme` would not inform the column type detection/validation which would result in numeric columns being falsely attributed to categorical (or raise an error if the type was specifically noted in a directive without a corresponding missing directive).
Noticed by @antgonza in [this forum post](https://forum.qiime2.org/t/q2-metadata-how-to-use-default-missing-scheme-and-column-missing-schemes/24255/5).
=> BUG: column type now informed by Metadata.load's `default_missing_scheme`

qiime2/core/path.py
Handle cross-device link errors when we attempt to symlink across devices by copying instead. This is particularly necessary for the cache.
=> IMP: Handle invalid cross device link errors

qiime2/core/archive/archiver.py, qiime2/core/cache.py, qiime2/core/testing/util.py, qiime2/core/tests/test_cache.py, qiime2/sdk/result.py
Get rid of race collision that can happen when you try to load the same artifact in several different processes at once by ensuring no process thinks the data is in the cache until the data is fully in cache/data.
=> Write collision

qiime2/core/testing/plugin.py, qiime2/plugin/plugin.py, qiime2/plugin/testing.py, qiime2/plugin/tests/test_plugin.py, qiime2/sdk/plugin_manager.py, qiime2/sdk/tests/test_plugin_manager.py
Adds support for registering descriptions and import examples for _artifact classes_. _Artifact class_ is a new term that we're using to refer to semantic types with a registered directory format. Previously these would be registered with `Plugin.register_semantic_type_to_format`, and that is still possible for backward compatibility. These can also now be registered with `Plugin.register_artifact_class`, which optionally takes a description and a dict of usage examples.  
Addresses #649.
=> adds support for registering descriptions and example imports for artifact classes

qiime2/sdk/tests/test_usage.py, qiime2/sdk/usage.py
Addresses #657 
Still needs:
Submitting a draft PR so we can use it in our usage sprint example.
=> imp: adds helpers to get metadata/artifacts from URLs in usage examples

qiime2/core/testing/format.py, qiime2/core/testing/plugin.py, qiime2/core/testing/transformer.py, qiime2/sdk/plugin_manager.py, qiime2/sdk/tests/test_plugin_manager.py
* Allows `PluginManager.get_formats` to take filters as strings to support easier access from outside of `qiime2`.
* Adds `PluginManager.get_exportable_formats` property, mirroring `PluginManager.get_importable_formats`
=> improve support for looking up formats

qiime2/core/tests/test_cache.py, qiime2/core/util.py
Currently setting permissions has been causing us some pain on panfs, and it doesn't necessarily seem to be gaining us anything, so we are disabling it at least for now.
=> SQUASH: Temporarily no op set_permissions

qiime2/core/cache.py, qiime2/core/path.py, qiime2/core/tests/test_cache.py, qiime2/core/util.py
Completely no-oping set permissions seemed to be causing some issues with backward compatibility. Caches could still have read-only artifacts in them, and we were unable to remove them because we were no longer setting them to rwx before trying to. This should resolve that. We now set rwx for user and group before trying to remove anything. Those are the only permissions settable with set_permissions
=> SQUASH: Can now only set rwx for user and group

.github/workflows/ci.yml, ci/recipe/meta.yaml, qiime2/sdk/usage.py
Fixes a usage example still using the moving-pictures metadata URL with the epoch interpolated.
=> SQUASH: Usage example fixed

qiime2/core/cache.py
Lock the cache when removing our process pool at exit to prevent the case where we remove an already tracked process pool out from under a different process that is garbage collecting.
=> BUG: Lock when removing the process pool in atexit

qiime2/core/testing/tests/test_mapped_actions.py, qiime2/core/tests/test_pipeline_resumption.py, qiime2/sdk/action.py, qiime2/sdk/parallel_config.py, qiime2/sdk/parsl_config.py, qiime2/sdk/tests/test_config.py
Loading configs in the way we initially envisioned is a bit more complex than we initially hoped. This got grosser than I intended. Refactors/unit tests will come tomorrow. Fortunately, we should not need this to start messing with Parsl.
=> SQUASH: Rework config loading

qiime2/sdk/parallel_config.py
Get rid of a deprecation warning about using the literal `None` versus the string 'none'
=> Use 'none'

qiime2/sdk/result.py, qiime2/sdk/tests/test_result.py
Add dunder contains to ResultCollection
Raise error if equality tested between a ResultCollection and anything but another ResultCollection or a dict
Ensure keys are strings in constructor
(various ResultCollection improvements/fixes)
=> Result collection fixes

ci/recipe/meta.yaml
Notebook version 7 appears to be the cause of the ModuleNotFound: notebook.base errors. For now at least the best solution is probably to just pin it. I tried looking through the Jupyter Notebook docs, and the docs for versions pre 7 404 when I try to select version 7.0.0. The docs that appear to be for version 7 make no reference to the IPythonHandler we are importing that leads to the errors.
=> Pin notebook <7 to prevent ModuleNotFound: notebook.base

ci/recipe/meta.yaml, qiime2/core/type/primitive.py, qiime2/core/type/util.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_result.py, qiime2/sdk/tests/test_util.py, qiime2/sdk/util.py
Ensure that result collection keys only contain the following characters: `A-Z`, `a-z`, `0-9`, `+`, `-`, `_`, and `.`.
Close #699
=> Validate result collection keys

ci/recipe/meta.yaml, qiime2/sdk/plugin_manager.py
Closes #514 by making the error message say the semantic type is not registered instead of saying it does not have a registered format.
Here's the thing about this. This error is being raised when a semantic type does not exist AND when a semantic type does not have a directory format. Currently, there does not seem to be a good way to tell if a semantic type has been registered without a corresponding format.
In other words, the previous error message was lying when the type itself wasn't registered. This one is lying when the type is registered but has no format. There doesn't seem to currently be a good way to distinguish between the two situations. I believe this error message will generally be less confusing in the scenarios where it is likely to be encountered.
=> Change error message

qiime2/core/testing/examples.py, qiime2/core/testing/plugin.py, qiime2/plugins.py, qiime2/sdk/result.py, qiime2/sdk/tests/test_usage.py, qiime2/sdk/usage.py, qiime2/tests/test_artifact_api.py
Adds ResultCollections to Usage API with the following steps (notes for myself while developing):
1. Change base Usage class to accept Collections
2. Implement in ExecutionUsage class
3. Use dummy plugin to test that this works
Co-Authored by: @Oddant1
=> NEW: adds ResultCollection to Usage API
