qiime/plugin.py
qiime/sdk/__init__.py
qiime/sdk/artifact.py
qiime/sdk/provenance.py
qiime/sdk/tests/test_artifact.py
qiime/sdk/tests/test_execution.py
qiime/sdk/tests/test_job.py
qiime/sdk/tests/test_plugin_manager.py
qiime/sdk/tests/test_provenance.py
qiime/sdk/tests/test_signature.py
qiime/sdk/tests/test_workflow.py
qiime/sdk/workflow.py
qiime/tests/test_plugin.py

Fixes #41. Pair-programmed with @gregcaporaso.

TST: add basic framework unit tests

---

.travis.yml
qiime/sdk/artifact.py

Necessary for NINJA-OPS plugin.

ENH: partially address #10

---

qiime/sdk/tests/test_execution.py
qiime/sdk/tests/test_workflow.py
qiime/sdk/workflow.py
qiime/tests/test_plugin.py

Note that this just adds the annotations - we're not doing anything with the view types yet.

ENH: adding view type annotation

---

qiime/sdk/execution.py
qiime/sdk/tests/test_execution.py

ENH: SubprocessExecutor.__call__ returns Job

---

qiime/__init__.py
qiime/core/type/__init__.py
qiime/core/type/grammar.py
qiime/core/type/primitive.py
qiime/core/type/semantic.py
qiime/core/type/signature.py
qiime/core/type/tests/test_grammar.py
qiime/core/type/tests/test_semantic.py
qiime/core/util.py
qiime/metadata.py
qiime/plugin.py
qiime/sdk/method.py

Further iteration of the type system.
Includes a new Signature object where type checking should occur.

Adds predicates, adds metadata

---

qiime/core/archiver.py
qiime/core/type/__init__.py
qiime/plugin.py

@ebolyen, can you review this one? I tested that this works with a new type that defines properties via the q2_types unit tests.

ENH: allowed definition of Properties in plugins

---

qiime/core/archiver.py

This fixes the two archiver bugs @ebolyen, @jakereps, and @ElDeveloper found. Not adding tests in this PR as I'm refactoring all tests in a separate branch, and the current tests are broken. I'll include test cases for these bugs in that PR.

BUG: support command-line zipped archives and nested data directories

---

qiime/core/archiver.py
qiime/core/type/__init__.py
qiime/core/type/primitive.py
qiime/core/util.py
qiime/plugin.py
qiime/sdk/__init__.py
qiime/sdk/method.py
qiime/sdk/plugin_manager.py

Pair programmed with @jairideout and @jakereps

ENH: adds parse_type and singleton PluginManager

---

qiime/plugin.py
qiime/sdk/method.py
qiime/sdk/visualizer.py
qiime/tests/test_artifact_api.py

~~Not even remotely ready for merge. This was just a quick hack that I wanted to share.~~
Questions:
- ~~What should the importable name be?~~
- What happens if a plugin imports another plugin's generated API?
- ~~Should visualizations and methods be separated?~~
- ~~Should plugins be able to define a hierarchical package structure?~~
Example:
```ipynb
In [1]: from qiime.plugin.feature_table import 
presence_absence    relative_frequency  
rarefy              summarize           
In [1]: from qiime.plugin.feature_table import rarefy
In [2]: rarefy?
Type:           Method
String form:    <qiime.sdk.method.Method object at 0x7fb2c688cef0>
File:           ~/qiime2/qiime2/qiime/sdk/method.py
Docstring:      <no docstring>
Call signature: rarefy(table:biom.table.Table, depth:int) -> …
```

ENH: initial artifact API

---

qiime/__init__.py

This will make things cleaner.

ENH: push Artifact/Visualization down to base package

---

qiime/__init__.py
qiime/core/type/signature.py
qiime/plugins.py
qiime/sdk/provenance.py
qiime/sdk/result.py
qiime/tests/test_artifact_api.py

Do not merge yet, this is for the demo and we might still need to change a few things.

ENH: better reprs and actions module for interactive use

---

qiime/sdk/method.py
qiime/sdk/result.py
qiime/sdk/visualizer.py

This is a toughy, @jairideout can you review?

MAINT: remove old todos

---

qiime/core/archiver.py
qiime/core/tests/test_archiver.py

Opening this as a placeholder for work right now. I based this initial cut off of #95, since both PRs introduce tests for `qiime.core`, and will rebase once #95 is merged.
This adds `default_flow_style` kwarg to the metadata YAML dump, which writes out standard YAML.

ENH: Pretty-print metadata YAML

---

qiime/sdk/__init__.py

Adds citation url, help page, and conda channel URLs to qiime.sdk
Resolves #80

ENH: Add helper URLs to qiime.sdk

---

qiime/sdk/result.py
qiime/sdk/tests/test_artifact.py
qiime/sdk/tests/test_visualization.py

Equality is defined by having the same type and UUID.

ENH: Artifact/Visualization __eq__/__ne__

---

qiime/core/util.py
qiime/sdk/result.py

ENH: Make formats smarter

---

qiime/core/type/signature.py
qiime/core/type/tests/test_signature.py
qiime/sdk/tests/test_method.py
qiime/sdk/tests/test_visualizer.py

I have added defaults to the PipelineSignature classes so that they can be exposed in q2cli. Happy to make any changes.

ENH: added defaults to qiime.core.type.signature classes

---

qiime/util.py

pair-programmed with @jairideout and @ebolyen

ENH: ports and improves redirected_stdio from qiime-studio

---

qiime/core/type/signature.py

fixes #144 
I tested this locally by modifying an existing method to have a default parameter of `None`.

ENH: adds support for None as default value

---

qiime/core/archive/__init__.py
qiime/core/archive/archiver.py
qiime/core/archive/format/v1.py
qiime/core/archive/provenance.py
qiime/core/archive/tests/test_archiver.py
qiime/core/archive/tests/test_provenance.py
qiime/core/callable.py
qiime/core/testing/method.py
qiime/core/testing/plugin.py
qiime/core/tests/test_util.py
qiime/core/transform.py
qiime/core/util.py
qiime/plugin/plugin.py
qiime/plugin/tests/test_plugin.py
qiime/plugins.py
qiime/sdk/result.py
qiime/sdk/tests/test_artifact.py
qiime/sdk/tests/test_method.py
qiime/sdk/tests/test_result.py
qiime/sdk/tests/test_visualization.py
qiime/sdk/tests/test_visualizer.py
setup.py

ENH: add decentralized provenance tracking

---

qiime/core/archive/provenance.py

this is @ebolyen's fix, written on my computer

BUG: provenance now handles metadata (category) of None

---

qiime2/metadata.py
qiime2/tests/test_metadata.py

`qiime2.Metadata.ids(where=None)` retrieves IDs matching optional search criteria.
This method was ported from `q2_feature_table._filter._ids_where` and updated to return a `set` of IDs. It also supports `where=None` which avoids any filtering of IDs.

ENH: add qiime2.Metadata.ids() method

---

qiime2/metadata.py
qiime2/tests/test_metadata.py

If the metadata index had no name (`pd.Index.name is None`), `qiime.Metadata.ids(where=where)` would always return `{'None'}` instead of the correct result.

BUG: support metadata querying with unnamed index

---

qiime2/core/type/primitive.py

pair-programmed with @ebolyen.

BUG: fix issue with handling of ranges with indefinite bounds

---

.travis.yml
ci/recipe/meta.yaml

Paired with @thermokarst and @ebolyen.

CI: travis now builds and tests conda package!

---

.travis.yml
ci/environment.yaml
ci/recipe/meta.yaml

Pair programmed with @ebolyen and @jairideout

CI: Leveraging conda environment.yaml 

---

qiime2/plugins.py

MAINT: fix deprecation warning

---

qiime2/core/archive/archiver.py
qiime2/core/archive/provenance.py
qiime2/core/path.py
qiime2/core/tests/test_path.py
qiime2/sdk/action.py
qiime2/sdk/result.py

This all still feels kind of gross to me.
fixes #223
fixes #181 (as far as I can tell)

BUG: fix tmp cleanup on failed and clean exits

---

qiime2/core/archive/archiver.py
qiime2/core/archive/format/v2.py
qiime2/core/archive/provenance.py
qiime2/core/archive/tests/test_provenance.py
qiime2/sdk/action.py

BUG: add output-name to provenance

---

qiime2/core/testing/format.py
qiime2/core/testing/plugin.py
qiime2/core/testing/transformer.py
qiime2/core/testing/type.py
qiime2/core/transform.py
qiime2/plugin/__init__.py
qiime2/plugin/model/__init__.py
qiime2/plugin/model/base.py
qiime2/plugin/model/directory_format.py
qiime2/plugin/model/file_format.py
qiime2/plugin/tests/test_plugin.py
qiime2/sdk/result.py
qiime2/sdk/tests/test_artifact.py
qiime2/sdk/tests/test_plugin_manager.py

Still needs some tests for each branch (and current testing formats should be updated)

ENH: adds validate protocol to plugin.model

---

qiime2/core/path.py

BUG: fix file descriptor resource leak in OutPath

---

qiime2/metadata/io.py
qiime2/metadata/tests/data/jagged-trailing-columns.tsv
qiime2/metadata/tests/test_metadata.py

Fixes #335, includes unit test.

BUG: Metadata support for jagged trailing empty columns

---

qiime2/metadata/base.py
qiime2/metadata/metadata.py

All public APIs have numpydoc docstrings. Some of the more important private APIs also have docstrings.

DOC: numpydoc docstrings on Metadata/MetadataColumn API

---

Makefile
scripts/activate_matplotlib.sh
scripts/activate_qiime2_envs.sh
scripts/deactivate_matplotlib.sh
scripts/deactivate_qiime2_envs.sh

fixes https://github.com/qiime2/q2-dada2/issues/68

ENH: override user pkg dirs for R/Python

---

qiime2/tests/test_util.py
qiime2/util.py

BUG: Copy if no write access

---

qiime2/core/testing/method.py
qiime2/core/testing/plugin.py
qiime2/plugin/tests/test_plugin.py
qiime2/sdk/action.py
qiime2/sdk/tests/test_method.py

BUG: Fixed docstring order in API

---

ci/recipe/meta.yaml

Pair programmed with @turanoo.

HACK: Pin `future` to old build

---

qiime2/core/type/primitive.py

`git blame` says that this code was last touched 2016-05-31 - yikes!

STY: Ancient indent error

---

ci/recipe/meta.yaml

Adding networkx for ~TypeMap~ ActionGraph

DEP: Add networkx dependency

---

qiime2/core/type/__init__.py
qiime2/core/type/util.py
qiime2/sdk/util.py

Related to https://github.com/qiime2/q2cli/pull/223

NEW: is_union helper

---

qiime2/core/testing/method.py
qiime2/core/testing/plugin.py
qiime2/core/util.py
qiime2/plugin/plugin.py
qiime2/plugin/tests/test_plugin.py
qiime2/sdk/action.py
qiime2/sdk/tests/test_action.py
setup.py

Begins to implement ability to deprecate plugin functionality

IMP: Add ability to deprecate plugin functionality

---

qiime2/core/type/primitive.py
qiime2/core/type/tests/test_primitive.py

This should correct the issue encountered here: 
https://forum.qiime2.org/t/error-running-qiime2-studio-bad-request/11548

BUG: fix broken decode in MetadataColumn[...]

---

qiime2/core/type/__init__.py
qiime2/core/type/util.py
qiime2/sdk/util.py

This PR is ported from https://github.com/qiime2/qiime2/pull/458

UTIL: is_metadata_column_type

---

qiime2/core/archive/provenance.py
qiime2/plugin/plugin.py
qiime2/sdk/action.py
qiime2/sdk/plugin_manager.py

Splitting this out into it's own PR. Still needs tests. This PR is ported from https://github.com/qiime2/qiime2/pull/458.

IMP: plugin manager improved API, internal cleanup

---

qiime2/core/testing/examples.py
qiime2/core/testing/plugin.py
qiime2/plugin/__init__.py
qiime2/plugin/plugin.py
qiime2/plugin/testing.py
qiime2/plugin/tests/test_tests.py
qiime2/plugins.py
qiime2/sdk/action.py
qiime2/sdk/tests/test_usage.py
qiime2/sdk/usage.py
qiime2/tests/test_artifact_api.py

NEW: Usage API

---

qiime2/core/testing/examples.py
qiime2/core/testing/plugin.py
qiime2/sdk/tests/test_usage.py
qiime2/sdk/usage.py
qiime2/tests/test_artifact_api.py

BUG: UsageInputs.validate - handle optional

---

qiime2/sdk/usage.py

LINT: remove dead code (Usage collections)

---

qiime2/sdk/plugin_manager.py

BUG: Fix reporting duplicated transformers

---

qiime2/core/testing/tests/test_mapped_actions.py
qiime2/core/type/signature.py

BUG: fix decode_parameters on signature

---

qiime2/plugins.py
qiime2/sdk/usage.py

A collection of minor tweaks impacting Usage
- closes #613 
- closes #612 
- some typos

Usage tweaks

---

qiime2/core/enan.py
qiime2/core/missing.py
qiime2/core/tests/test_enan.py
qiime2/core/tests/test_missing.py
qiime2/metadata/io.py
qiime2/metadata/metadata.py
qiime2/metadata/tests/data/invalid/missing-unknown-scheme.tsv
qiime2/metadata/tests/data/valid/missing-insdc.tsv
qiime2/metadata/tests/data/valid/override-insdc.tsv
qiime2/metadata/tests/test_io.py
qiime2/metadata/tests/test_metadata.py
qiime2/metadata/tests/test_metadata_column.py

Still a draft, will update with additional test and docs

NEW: per-column missing values (INSDC)

---

qiime2/core/cache.py

Resolve potential issues primarily related to running QIIME 2 in containers accessing the cache

Nonexistent user

---

qiime2/core/archive/archiver.py
qiime2/core/archive/tests/test_archiver.py
qiime2/jupyter/handlers.py

[BACKPORT] BUG: fix Jupyter reprs not loading because of Cache (#637)

---

qiime2/core/cache.py
qiime2/core/tests/test_cache.py

[PORT] BUG: fix multi-user cache permissions (#640)

---

qiime2-test-cache-/VERSION
qiime2/core/cache.py
qiime2/core/tests/test_cache.py

Add necessary documentation for the cache in a form that we can use for the dev docs.

Cache docs

---

qiime2/core/archive/archiver.py
qiime2/core/cache.py
qiime2/core/util.py
qiime2/sdk/result.py

Attempt to fix another race condition identified by @wasade on the forum.

Lock copy_to_data

---

qiime2/core/tests/test_cache.py
qiime2/core/util.py

Reverts qiime2/qiime2#666 Opening this up right now so it's already here if we choose to just revert this to resolve the issue

Revert "SQUASH: Temporarily no op set_permissions"

---

qiime2/core/archive/provenance.py
qiime2/core/cache.py
qiime2/core/testing/method.py
qiime2/core/testing/pipeline.py
qiime2/core/testing/plugin.py
qiime2/core/tests/test_cache.py
qiime2/core/type/__init__.py
qiime2/core/type/collection.py
qiime2/core/type/parse.py
qiime2/core/type/signature.py
qiime2/core/type/tests/test_util.py
qiime2/core/type/util.py
qiime2/plugin/__init__.py
qiime2/plugin/tests/test_plugin.py
qiime2/sdk/action.py
qiime2/sdk/tests/test_method.py
qiime2/sdk/tests/test_pipeline.py

Adds new Collection type to support collections of outputs

NEW: Start adding Collection

---

qiime2/core/type/signature.py
qiime2/sdk/proxy.py

__lower__ isn't a thing and we somehow didn't notice.

BUG: repr calls __lower__ not lower()

---

qiime2/core/testing/pipeline.py

Makes the de-facto dict keys in the dummy plugin strings

Use string keys

---

qiime2/core/type/primitive.py
qiime2/core/type/util.py
qiime2/sdk/result.py

Making a few linting adjustments due to suspected pep8 updates causing linting failures.

NOQA: fixing some pep8 failures
